### 🔹 File: `task1_arrays.py`

In [3]:
import numpy as np

# 1D array
arr1 = np.arange(1, 11)

# 2D array
arr2 = np.arange(1, 10).reshape(3, 3)

# 3D array
arr3 = np.random.rand(3, 5, 3)

# Shape, size, dtype
print("Array 1:", arr1.shape, arr1.size, arr1.dtype)
print("Array 2:", arr2.shape, arr2.size, arr2.dtype)
print("Array 3:", arr3.shape, arr3.size, arr3.dtype)

Array 1: (10,) 10 int32
Array 2: (3, 3) 9 int32
Array 3: (3, 5, 3) 45 float64


### 🔹 File: `task2_indexing_slicing.py`

In [4]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print("First three elements:", data[:3])
print("Every alternate element:", data[::2])
print("Reversed array:", data[::-1])

First three elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


### 🔹 File: `task3_math_operations.py`

In [5]:
import numpy as np

A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)
print("Dot product:", np.dot(A, B))
print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Std of A:", np.std(A))
print("Variance of A:", np.var(A))
print("Max of B:", np.max(B), "at index", np.argmax(B))
print("Min of B:", np.min(B), "at index", np.argmin(B))

A: [ 8 20 10 19 12]
B: [16  5  7  5  9]
Addition: [24 25 17 24 21]
Subtraction: [-8 15  3 14  3]
Multiplication: [128 100  70  95 108]
Division: [0.5        4.         1.42857143 3.8        1.33333333]
Dot product: 501
Mean of A: 13.8
Median of A: 12.0
Std of A: 4.833218389437829
Variance of A: 23.360000000000003
Max of B: 16 at index 0
Min of B: 5 at index 1


### 🔹 File: `task4_reshape_transpose.py`

In [6]:
import numpy as np

arr = np.arange(1, 13)
reshaped_2d = arr.reshape(4, 3)
reshaped_3d = arr.reshape(2, 2, 3)
transposed = reshaped_2d.T

print("2D Reshape:", reshaped_2d)
print("3D Reshape:", reshaped_3d)
print("Transposed:", transposed, "Shape:", transposed.shape)

2D Reshape: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3D Reshape: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Transposed: [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] Shape: (3, 4)


### 🔹 File: `task5_boolean_masking.py`

In [7]:
import numpy as np

arr = np.random.randint(10, 51, 15)

print("Original:", arr)
print("Greater than 25:", arr[arr > 25])
arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)
print("Divisible by 5 count:", np.sum(arr % 5 == 0))

Original: [41 39 33 49 21 41 38 27 46 39 11 46 19 20 34]
Greater than 25: [41 39 33 49 41 38 27 46 39 46 34]
After replacing <30 with 0: [41 39 33 49  0 41 38  0 46 39  0 46  0  0 34]
Divisible by 5 count: 5


### 🔹 File: `task6_built_in_functions.py`

In [8]:
import numpy as np

equally_spaced = np.linspace(0, 1, 10)
identity = np.eye(4)
rand_arr = np.random.randint(1, 101, 20)
sorted_arr = np.sort(rand_arr)
largest_5 = sorted_arr[-5:]

print("Equally spaced:", equally_spaced)
print("Identity matrix:", identity)
print("Sorted array:", sorted_arr)
print("5 largest:", largest_5)

Equally spaced: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted array: [ 4  5  7 20 21 39 41 42 47 49 50 55 56 57 64 64 66 80 82 94]
5 largest: [64 66 80 82 94]


### 🔹 File: `task7_generic.py`

In [9]:
import numpy as np
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start = time.time()
C = np.dot(A, B)
end = time.time()

try:
    det = np.linalg.det(C)
    inv = np.linalg.inv(C)
except np.linalg.LinAlgError:
    det = "Not computable"
    inv = "Not invertible"

print("Time taken:", end - start)
print("Determinant:", det)
print("Inverse status:", "Computed" if isinstance(inv, np.ndarray) else inv)

Time taken: 0.0030024051666259766
Determinant: 2.2203855297854128e+51
Inverse status: Computed
